### ISSUE TITLE
Missing d.ts file in most libraries

### ISSUE THREAD

**Issue by jsobell** [aurelia/pal#14]
I'm not sure where to post this issues, as it applies to most of the new distros, but since it first appeared in this module I'll post it here.
We've been through the drama about what happened to `aurelia-pal.d.ts`, but the problem exists in most of the new distros, and I think it's quite a simple fix.
I know Microsoft recommend adding the typings attribute to the package.json, and NPM changes its behavior based on the moduleResolution settings, but a catch-all (which works in every case I've experienced so far) is to do the following:
- A file name module_name.d.ts is defined at the root of the package - Yes, that's not all that important, but it's the most common method, and causes no issues
- A file named index.d.ts is also created, containing `export * from './module_name.d.ts';` which should keep all the node resolution users happy.

If we really don't want the definitions at the root, let's have a stub pointer called module_name.d.ts containing `export * from './dist/whatever/module_name.d.ts';`.

The key thing seems to be that the type definition source resolution works differently in different development environments, and the current method just doesn't work for many people, and forcing people to specify a particular moduleResolution in their package file will break usage of other modules.
I'm no guru on this stuff, but I am being badly impacted by it.  We've now pretty much given up on webpack, particularly after seeing the CLI using RequireJS, but even the CLI versions won't compile unless the current typings configuration changes.

**Comment by EisenbergEffect** [comment]
All repos now use the typings field which is picked up automatically by any npm-based system such as Webpack and the CLI. We also provide the typings.json file so that the typings tool can be used for all other scenarios.
