### ISSUE TITLE
pal implementation for web/service workers 

### ISSUE THREAD

**Issue by alexisargyris** [aurelia/pal#15]
Following [this ](http://stackoverflow.com/questions/38290142/error-reflect-definemetadata-while-trying-to-load-a-transient-web-worker) discussion you may want to consider a PAL implementation specifically for web workers.

The requirement came up while trying to decorate a worker's class as transient.

**Comment by EisenbergEffect** [comment]
Yes, absolutely. It's not at the top of our list, but if someone from the community wants to start in on it, we'd be glad to help them along.

**Comment by EisenbergEffect** [comment]
We've got this :)
