### ISSUE TITLE
Platform.global implementation breaks Chrome Apps CSP

### ISSUE THREAD

**Issue by AshleyGrant** [aurelia/pal#25]
**I'm submitting a bug report**

* **Library Version:**
1.3.0

**Please tell us about your environment:**
* **Operating System:**
all

* **Node Version:**
n/a

* **NPM Version:**
n/a

* **JSPM OR Webpack AND Version**
n/a

* **Browser:**
Chrome Web Apps

* **Language:**
all

**Current behavior:**
According to https://github.com/paulmillr/es6-shim/issues/301 and https://github.com/tc39/proposal-global, our current implementation for finding the global will fail when run in Chrome Web Apps due to a CSP issue.

**Expected/desired behavior:**
For it to work in all possible environments

es6-shim uses the following:
var getGlobal = function () {
	// the only reliable means to get the global object is
	// `Function('return this')()`
	// However, this causes CSP violations in Chrome apps.
	if (typeof self !== 'undefined') { return self; }
	if (typeof window !== 'undefined') { return window; }
	if (typeof global !== 'undefined') { return global; }
	throw new Error('unable to locate global object');
};

(pulled from https://github.com/tc39/proposal-global )

* **What is the motivation / use case for changing the behavior?**
Allow Aurelia to work everywhere possible

**Comment by EisenbergEffect** [comment]
@AshleyGrant Can you submit a PR?

**Comment by Alexander-Taran** [comment]
seems kinda done
https://github.com/aurelia/pal/blob/0e643f029001f5f4f4011a9f954b53dcec51c9ac/src/index.js#L235

**Comment by EisenbergEffect** [comment]
@AshleyGrant Can you confirm and close if we're good?

**Comment by AshleyGrant** [comment]
Looks like it is missing

`if (typeof window !== 'undefined') { return window; }`

**Comment by EisenbergEffect** [comment]
Who wants to submit a PR?

**Comment by EisenbergEffect** [comment]
No PR after a year, so closing.

**Comment by AshleyGrant** [comment]
Given that Chrome Web Apps have been deprecated, I don't see any reason to fix this, so I'm fine with the closure.
