### ISSUE TITLE
Possibility to take AggregateError to `aurelia-exception` or something more generic?

### ISSUE THREAD

**Issue by unional** [aurelia/pal#3]
Hi @EisenbergEffect,

`AggregateError` is more generic than `pal` and I would suggest to put it further down to a lower level module.
`dependency-injection` currently depends on `pal` because of it.
While `pal` is fairly generic, it still comes with specific ideology such as those in the `Dom` interface.

I want to use the `dependency-injection` module for my application but want to avoid getting `pal` along with it.

I understand it is not the intended usage of `aurelia` to just using the DI module, but would you consider doing this?

Thanks,
Unional

**Comment by EisenbergEffect** [comment]
It's generally not considered a best practice to have modules that are so fine-grained as to include only one function. So, we aren't going to do that.

However, if you want to use DI you can still do that. The PAL only defines "interfaces". There isn't really any code in there. The implementation is in pal-browser, which you don't need to use DI.

**Comment by unional** [comment]
Please ignore, as `metadata` also relies on `pal` because of `PLATFORM`. Maybe it's too much to ask. :)

Keep up the good work. :+1:

**Comment by unional** [comment]
Thanks! and Thanks for the quick response! :+1:

**Comment by unional** [comment]
If it wasn't for specific requirement of our product, I would use `aurelia` for it. :( 
`aurelia` is a well thought out framework.
