### ISSUE TITLE
TypeScript's emitDecoratorMetadata produces client-only globals

### ISSUE THREAD

**Issue by michaelbull** [aurelia/pal#34]
**I'm submitting a bug report**

* **Library Version:**
1.5.0

**Please tell us about your environment:**
* **Operating System:**
Linux F26

* **Node Version:**
8.9.4

* **NPM Version:**
5.6.0

* **JSPM OR Webpack AND Version**
webpack 3.11.0

* **Browser:**
all 

* **Language:**
TypeScript 2.7.2

**Current behavior:**
I am using the `emitDecoratorMetadata` compiler option in my TypeScript application to leverage the `@autoinject` decorator where appropriate. The `emitDecoratorMetadata` option is currently producing browser-only globals. In the custom element below I have explicitly avoided using `autoinject` and instead manually injected `DOM.Element` - however it is still producing some decorator metadata which references the `Element` type:

###### Source

```typescript
@inject(DOM.Element)
@customAttribute('zoom')
export class Zoom {
    element: Element;

    constructor(element: Element) {
        this.element = element;
    }
```

###### Transpiled

```javascript
e = i([o.inject(o.DOM.Element), o.customAttribute('zoom'), r('design:paramtypes', [Element])], e);
```

---

I have also tried typing the `element` field as follows:

```typescript
@inject(DOM.Element)
@customAttribute('zoom')
export class Zoom {
    element: DOM.Element;

    constructor(element: DOM.Element) {
        this.element = element;
    }
```

However this produces the following TypeScript error:

```
TS2503: Cannot find namespace 'DOM'.
```

**Expected/desired behavior:**

* **What is the expected behavior?**

There should be some mechanism for using `DOM.Element` as an actual property type in TypeScript, as then the emitted decorator metadata would align with the `DOM.Element` type in `PAL` and not the `Element` type from the browser.

**Comment by EisenbergEffect** [comment]
Will this work: `constructor(element: typeof DOM.Element)` ?

**Comment by michaelbull** [comment]
@EisenbergEffect I tried that, and it then stopped me using any methods that actually exist on the `Element` type:

```
ERROR in [at-loader] ./src/components/example.ts:27:22 
    TS2339: Property 'classList' does not exist on type '{ new (): Element; prototype: Element; }'.

ERROR in [at-loader] ./src/components/example.ts:33:22 
    TS2339: Property 'addEventListener' does not exist on type '{ new (): Element; prototype: Element; }'.

ERROR in [at-loader] ./src/components/example.ts:37:22 
    TS2339: Property 'removeEventListener' does not exist on type '{ new (): Element; prototype: Element; }'.
```

My current solution is to keep the manual `@inject(DOM.Element)`, but to type the property in the class (and in the constructor), to `any` - which isn't desirable.

**Comment by EisenbergEffect** [comment]
I suppose you could cast it before assigning in the constructor. Not ideal, but a little better.

**Comment by michaelbull** [comment]
That'll do for now. Thanks @EisenbergEffect.
