### ISSUE TITLE
setTimeout / setInterval

### ISSUE THREAD

**Issue by jdanyow** [aurelia/pal#5]
binding and the task queue may use setTimeout in some fallback scenarios.  Should we add these methods to the PAL?  Also: http://stackoverflow.com/questions/34841734/how-to-abstract-away-the-usage-of-browsers-window-object/34842796

**Comment by EisenbergEffect** [comment]
Yes. I can merge that as soon as we have the PR

**Comment by EisenbergEffect** [comment]
Any opportunity to submit a PR for this @jdanyow ?

**Comment by EisenbergEffect** [comment]
@jdanyow Will you have a chance to PR this before RC?

**Comment by doktordirk** [comment]
there is though allready PLATFORM.global.setTimeout etc

**Comment by EisenbergEffect** [comment]
I think we can forgo this for the immediate future. If we have an issue, we can add it later.
