### ISSUE TITLE
.d.ts build 

### ISSUE THREAD

**Issue by behzad888** [aurelia/pal#9]
In some Aurelia libraries when build and generate .d.ts, sometimes observed duplicate comments.

like:
[Line42](https://github.com/aurelia/pal/blob/master/dist/aurelia-pal.d.ts#L42) and [Line45](https://github.com/aurelia/pal/blob/master/dist/aurelia-pal.d.ts#L45)

**Comment by EisenbergEffect** [comment]
@cmichaelgraham Please look into this.

**Comment by EisenbergEffect** [comment]
This has been fixed and we'll be updating shortly.
